image: rikorose/gcc-cmake

before_script:
  - apt-get update -qq && apt-get install -y -qq cppcheck vera++ clang-tidy
  - g++ --version
  - cppcheck --version
  - vera++ --version
  - cp ci/vera.profile /usr/lib/vera++/profiles/custom

build:
  script:
    - cmake . -DCMAKE_CXX_FLAGS="-Werror"
    - make -j4
    - make clean
    - cmake . -DCMAKE_CXX_FLAGS="-Wall -Wextra" # Build again, but with more warnings
    - make -j4

cppcheck:
  script:
    - bash -x ci/cppcheck.sh

vera:
  script:
    - bash -x ci/vera.sh

clang-tidy:
  script:
    - bash -x ci/clang-tidy.sh
