variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Global caching directive for pip
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .cache/pip

stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update -qq && apt-get -qq -y install libstdc++6 python3-pip && python3 -m pip install --upgrade pip
  - python3 -V
  - python3 -m pip --version
  - g++ --version
  - cat /etc/*-release
  - python3 -m pip install gcovr

build:
  image: spacedot/cppcheck:2.5
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    GCC_COLORS: "error=31;1:warning=35;1:note=36;1:range1=32:range2=34:locus=39;1:quote=39;1:fixit-insert=32:fixit-delete=31:diff-filename=39;1:diff-hunk=32:diff-delete=31:diff-insert=32:type-diff=32;1"
    CLICOLOR_FORCE: 1 # Necessary for cmake to output colours
  script:
    - cmake . -DCMAKE_CXX_FLAGS="-Werror -fdiagnostics-color=always"
    - make -j4
    - make clean
    - cmake . -DCMAKE_CXX_FLAGS="-Wall -Wextra -fdiagnostics-color=always" # Build again, but with more warnings
    - make -j4

tests:
  image: lightspot21/acubesat-ci:latest
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - cmake .
    - make tests -j4
    - ./tests --use-colour yes  # Run the tests
  after_script:
    - ./tests -r junit -o junit.xml
  artifacts:
    expire_in: 1 week
    reports:
      junit: junit.xml

cppcheck:
  image: spacedot/cppcheck:2.5
  stage: build
  before_script:
    - cppcheck --version
  script:
    - echo -e "\u001b[34;1mStarting cppcheck...\u001b[0m"
    - echo -e "\u001b[34;1mRunning cppcheck with default checklist...\u001b[0m"
    - cd "$(dirname "$0")/.."
    - cppcheck --enable=all --suppress=unusedFunction --suppress=noExplicitConstructor --force \
     --inline-suppr --error-exitcode=1 -I inc src test
    - echo -e "\u001b[34;1mRunning cppcheck with misra addon...\u001b[0m"
    - cppcheck --addon=misra --suppress=misra-c2012-3.1 --suppress=misra-c2012-5.1 --suppress=misra-c2012-5.2 \
     --suppress=misra-c2012-5.3 --suppress=misra-c2012-12.3 --suppress=misra-c2012-13.4 --suppress=misra-c2012-14.4 \
     --suppress=misra-c2012-15.5 --suppress=misra-c2012-16.3 --suppress=misra-c2012-18.4 --suppress=misra-c2012-18.8 -I inc src test

clang-tidy:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    TERM: xterm-color
  script:
    - ci/clang-tidy.sh

pages:
  image: lightspot21/acubesat-ci:latest
  stage: deploy
  when: always  # Deploy always and on build or test failure, generate just the documentation
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - public
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - ./ci/pages_deploy.sh
    - echo -e "\e[1;36mPublic directory contents\e[0m" && ls -l public/coverage  # Print directory contents for debugging
  artifacts:
    paths:
      - public # Upload the resulting website
  only:
    - branches # Deploy on all branches
