#ifndef ECSS_SERVICES_ONBOARDMONITORINGSERVICE_HPP
#define ECSS_SERVICES_ONBOARDMONITORINGSERVICE_HPP


class OnBoardMonitoringService : public Service{

};

#endif // ECSS_SERVICES_ONBOARDMONITORINGSERVICE_HPP
