#ifndef ECSS_SERVICES_ECSS_DEFINITIONS_H
#define ECSS_SERVICES_ECSS_DEFINITIONS_H

// Todo: Specify maximum size for regular messages
#define ECSS_MAX_MESSAGE_SIZE 1024

#define ECSS_MAX_STRING_SIZE 256

// 7.4.1
#define CCSDS_PACKET_VERSION 0

// 7.4.4.1c
#define ECSS_PUS_VERSION 2

#endif //ECSS_SERVICES_ECSS_DEFINITIONS_H
