#ifndef ECSS_SERVICES_ECSS_DEFINITIONS_H
#define ECSS_SERVICES_ECSS_DEFINITIONS_H

// Todo: Specify maximum size for regular messages
#define ECSS_MAX_MESSAGE_SIZE 1024

#endif //ECSS_SERVICES_ECSS_DEFINITIONS_H
